#!/bin/bash

name="gpu"
build_dir="../../bin/${name}/"
this_dir="$(pwd)"

extensions="-g"
optimizations="-O0"
libs="-lm"
warns="-Wall -Wextra -Wno-unused-parameter -Wno-switch"
stripping="-fno-rtti -fno-exceptions"
includes="-I../../src/include"
defs=""

xlinker="$libs"
xcompiler="-fPIC $extensions $optimizations $warns $stripping $defs $includes"
cudalibs="-lcudart"

cudaflags="-G -g --keep"

if [ ! -d "$build_dir" ]; then
    mkdir -p "$build_dir"
fi

pushd "$build_dir" 1>> /dev/null
    nvcc $cudaflags -ccbin "g++" -Xcompiler "$xcompiler" -dc "${this_dir}/${name}.cu" -o "${name}.o" && \
    nvcc $cudaflags -ccbin "g++" -Xcompiler "$xcompiler" -shared -o "${name}.so" "${name}.o" $cudalibs -Xlinker "$xlinker" && \
    cp "${name}.so" ../../data/
popd 1>> /dev/null

