#!/bin/bash

name="gpu"
build_dir="../../bin/${name}/"
this_dir="$(pwd)"

extensions="-msse -mavx -march=native"
optimizations="-O3 -ftree-vectorize"
libs="-lm"
warns="-Wall -Wextra -Wno-unused-parameter -Wno-switch -fdiagnostics-show-option"
stripping="-fno-rtti -fno-exceptions"
includes="-I../../src/include"
defs="-DMUTATION_CHANCE=0.5f -DACCEPT_WORSE_CHANCE=0.05f"

xlinker="$libs"
xcompiler="-fPIC $extensions $optimizations $warns $stripping $defs $includes"
cudalibs="-lcudart"

cudaflags="-Xptxas -v --gpu-architecture=sm_60 --keep"

if [ ! -d "$build_dir" ]; then
    mkdir -p "$build_dir"
fi

pushd "$build_dir" 1>> /dev/null
    nvcc $cudaflags -ccbin "g++" -Xcompiler "$xcompiler" -dc "${this_dir}/${name}.cu" -o "${name}.o" && \
    nvcc $cudaflags -ccbin "g++" -Xcompiler "$xcompiler" -shared -o "${name}.so" "${name}.o" $cudalibs -Xlinker "$xlinker" && \
    cp "${name}.so" ../../data/
popd 1>> /dev/null

