#!/bin/bash

build_dir="../../bin/main/"
this_dir="$(pwd)"

extensions="-g"
optimizations="-O0"
libs=""
warns="-Wall -Wextra -Wno-unused-parameter -Wno-switch"
stripping="-fno-rtti -fno-exceptions"
includes=""
defs=""

if [ ! -d "$build_dir" ]; then
    mkdir -p "$build_dir"
fi

pushd "$build_dir"
    g++ $extensions $optimizations $warns $stripping $defs "${this_dir}/main.cpp" -o main $includes $libs
popd
