#!/bin/bash

build_dir="../../bin/"
this_dir="$(pwd)"

extensions="-msse -mavx -march=native"
optimizations="-O3 -march=native -ftree-vectorize -funroll-loops"
libs="-ldl"
warns="-Wall -Wextra -Wno-unused-parameter -Wno-switch"
stripping="-fno-rtti -fno-exceptions"
includes="-I../src/include"
defs=""

if [ ! -d "$build_dir" ]; then
    mkdir -p "$build_dir"
fi

pushd "$build_dir" 1>> /dev/null
    g++ $extensions $optimizations $warns $stripping $defs "${this_dir}/main.cpp" -o main $includes $libs && \
        cp main ../data/
popd 1>> /dev/null
