#!/bin/bash

name="cpupar"
build_dir="../../bin/${name}/"
this_dir="$(pwd)"

extensions="-g"
optimizations="-O0"
libs="-lm"
warns="-Wall -Wextra -Wno-unused-parameter -Wno-switch"
stripping="-fno-rtti -fno-exceptions"
includes="-I../../src/include"
defs=""

if [ ! -d "$build_dir" ]; then
    mkdir -p "$build_dir"
fi

pushd "$build_dir" 1>> /dev/null
    g++ -fopenmp -c -fPIC $extensions $optimizations $warns $stripping $defs "${this_dir}/${name}.cpp" -o "${name}.o" $includes && \
    g++ -fopenmp -shared -o "${name}.so" "${name}.o" $libs && \
    cp "${name}.so" ../../data/
popd 1>> /dev/null
